Repository seoljuyeon/Algorithm-study, pull requests merged in 2024-04, with the labels that each got.

#67 [주연] 240401 - 38, 39
  src/juyeon/PGS/gilbut/dp/P38_피보나치_수.java
  src/juyeon/PGS/gilbut/dp/P39_정수_삼각형.java
Labels: problems, 설주연

#68 [솔이] 240401 - 38, 39
  src/soli/PGS/ch8_dp/PGS38.java
  src/soli/PGS/ch8_dp/PGS39.java
Labels: problems, 최솔이

#69 [주연] 240404 - 40
  src/juyeon/PGS/gilbut/dp/P40_등굣길.java
Labels: problems, 설주연

#70 [솔이] 240404 - 40
  src/soli/PGS/ch8_dp/PGS40.java
Labels: problems, 최솔이

#71 [주연] 240408 - 42, 43, 44
  src/juyeon/PGS/gilbut/dataStructure/P42_올바른_괄호.java
  src/juyeon/PGS/gilbut/dataStructure/P43_괄호_회전하기.java
  src/juyeon/PGS/gilbut/dataStructure/P44_주식가격.java
Labels: problems, 설주연

#72 [솔이] 240408 - 42, 43, 44
  src/soli/PGS/ch9_data_structure/PGS42.java
  src/soli/PGS/ch9_data_structure/PGS43.java
  src/soli/PGS/ch9_data_structure/PGS44.java
Labels: problems, 최솔이

#74 [주연] 240411 - 기능 개발, 다리를 지나는 트럭
  src/juyeon/PGS/gilbut/dataStructure/P45_기능개발.java
  src/juyeon/PGS/gilbut/dataStructure/P46_다리를_지나는_트럭.java
Labels: problems, 설주연

#75 [솔이] 240415 - 47, 48
  src/soli/PGS/ch9_data_structure/PGS47.java
  src/soli/PGS/ch9_data_structure/PGS48.java
Labels: problems, 최솔이

#76 [주연] 240418 - 50, 51
  src/juyeon/PGS/gilbut/dataStructure/P50_이중_우선순위_큐.java
  src/juyeon/PGS/gilbut/dataStructure/P51_디스크_컨트롤러.java
Labels: problems, 설주연

#79 [주연] 240425 - 52, 54
  src/juyeon/PGS/gilbut/dataStructure/P52_보석_쇼핑.java
  src/juyeon/PGS/gilbut/dataStructure/P54_호텔_방_배정.java
Labels: problems, 설주연

#78 [솔이] 240425 - 52, 53
  src/soli/PGS/ch9_data_structure/PGS52.java
  src/soli/PGS/ch9_data_structure/PGS53.java
Labels: 최솔이

#80 [주연] 연습 🐥🐥🐥
  src/juyeon/PGS/drill/PGS_주사위_게임_3.java
  src/juyeon/PGS/drill/PSG_간단한_식_계산하기.java
  src/juyeon/PGS/gilbut/dataStructure/P47_순위.java
Labels: problems, 설주연

#81 [주연] 240429 - 53, 55
  src/juyeon/PGS/gilbut/dataStructure/P53_섬_연결하기.java
  src/juyeon/PGS/gilbut/dataStructure/P55_가사_검색.java
Labels: problems, 설주연
